-- ============================================
-- إنشاء جدول بيانات السيرفرات
-- ============================================

-- تفعيل pgcrypto للتشفير
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- إنشاء جدول بيانات السيرفرات
CREATE TABLE IF NOT EXISTS بيانات_السيرفر (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    رقم_الفرع TEXT UNIQUE NOT NULL,
    اسم_الفرع_ar TEXT NOT NULL,
    اسم_الفرع_en TEXT NOT NULL CHECK (اسم_الفرع_en = UPPER(اسم_الفرع_en)),
    اسم_اليوزر TEXT NOT NULL,
    باسوورد TEXT NOT NULL, -- سيتم تشفيره
    تاريخ_الانشاء TIMESTAMPTZ DEFAULT NOW(),
    حالة_اليوزر TEXT NOT NULL CHECK (حالة_اليوزر IN ('الافتتاح قريبا', 'يعمل', 'مغلق مؤقتا', 'مغلق نهائيا'))
);

-- إنشاء دالة لتشفير الباسوورد
CREATE OR REPLACE FUNCTION encrypt_password(password TEXT)
RETURNS TEXT AS $$
BEGIN
    RETURN pgp_sym_encrypt(password, 'sols-encryption-key');
END;
$$ LANGUAGE plpgsql;

-- إنشاء دالة لفك تشفير الباسوورد
CREATE OR REPLACE FUNCTION decrypt_password(encrypted_password TEXT)
RETURNS TEXT AS $$
BEGIN
    RETURN pgp_sym_decrypt(encrypted_password::bytea, 'sols-encryption-key');
END;
$$ LANGUAGE plpgsql;

-- إنشاء Trigger لتشفير الباسوورد تلقائياً قبل الإدراج
CREATE OR REPLACE FUNCTION encrypt_password_before_insert()
RETURNS TRIGGER AS $$
BEGIN
    NEW.باسوورد = encrypt_password(NEW.باسوورد);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- إنشاء Trigger لتشفير الباسوورد تلقائياً قبل التعديل
CREATE OR REPLACE FUNCTION encrypt_password_before_update()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.باسوورد IS DISTINCT FROM OLD.باسوورد THEN
        NEW.باسوورد = encrypt_password(NEW.باسوورد);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- تطبيق الـ Triggers على الجدول
DROP TRIGGER IF EXISTS trigger_encrypt_password_insert ON بيانات_السيرفر;
CREATE TRIGGER trigger_encrypt_password_insert
    BEFORE INSERT ON بيانات_السيرفر
    FOR EACH ROW
    EXECUTE FUNCTION encrypt_password_before_insert();

DROP TRIGGER IF EXISTS trigger_encrypt_password_update ON بيانات_السيرفر;
CREATE TRIGGER trigger_encrypt_password_update
    BEFORE UPDATE ON بيانات_السيرفر
    FOR EACH ROW
    EXECUTE FUNCTION encrypt_password_before_update();

-- ============================================
-- إعداد سياسات RLS (Row Level Security)
-- ============================================

-- تفعيل RLS على الجدول
ALTER TABLE بيانات_السيرفر ENABLE ROW LEVEL SECURITY;

-- سياسة السماح للمستخدمين المسجلين بالقراءة
CREATE POLICY "allow_authenticated_read"
    ON بيانات_السيرفر FOR SELECT
    TO authenticated
    USING (true);

-- سياسة السماح للمديرين فقط بالإضافة
CREATE POLICY "allow_admin_insert"
    ON بيانات_السيرفر FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM auth.users
            WHERE auth.users.id = auth.uid()
            AND auth.users.raw_user_meta_data->>'role' = 'admin'
        )
    );

-- سياسة السماح للمديرين فقط بالتعديل
CREATE POLICY "allow_admin_update"
    ON بيانات_السيرفر FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM auth.users
            WHERE auth.users.id = auth.uid()
            AND auth.users.raw_user_meta_data->>'role' = 'admin'
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM auth.users
            WHERE auth.users.id = auth.uid()
            AND auth.users.raw_user_meta_data->>'role' = 'admin'
        )
    );

-- سياسة السماح للمديرين فقط بالحذف
CREATE POLICY "allow_admin_delete"
    ON بيانات_السيرفر FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM auth.users
            WHERE auth.users.id = auth.uid()
            AND auth.users.raw_user_meta_data->>'role' = 'admin'
        )
    );

-- ============================================
-- إدخال بيانات تجريبية
-- ============================================

INSERT INTO بيانات_السيرفر (رقم_الفرع, اسم_الفرع_ar, اسم_الفرع_en, اسم_اليوزر, باسوورد, حالة_اليوزر) VALUES
    ('BR001', 'فرع الرياض', 'RIYADH', 'admin_riyadh', 'SecurePass123!', 'يعمل'),
    ('BR002', 'فرع جدة', 'JEDDAH', 'admin_jeddah', 'Jeddah@2024', 'يعمل'),
    ('BR003', 'فرع الدمام', 'DAMMAM', 'admin_dammam', 'Dammam#456', 'الافتتاح قريبا'),
    ('BR004', 'فرع مكة', 'MAKKAH', 'admin_makkah', 'Makkah@789', 'مغلق مؤقتا');

-- ============================================
-- إنشاء Views للتقارير
-- ============================================

-- تقرير بعدد اليوزرات حسب الحالة
CREATE OR REPLACE VIEW تقرير_اليوزرات_حسب_الحالة AS
SELECT 
    حالة_اليوزر,
    COUNT(*) as عدد_اليوزرات,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) as النسبة_المئوية
FROM بيانات_السيرفر
GROUP BY حالة_اليوزر
ORDER BY COUNT(*) DESC;

-- تقرير بالأفرع المنشأة خلال فترة محددة
CREATE OR REPLACE FUNCTION تقرير_الأفرع_حسب_الفترة(تاريخ_البداية TIMESTAMPTZ, تاريخ_النهاية TIMESTAMPTZ)
RETURNS TABLE (
    رقم_الفرع TEXT,
    اسم_الفرع_ar TEXT,
    اسم_الفرع_en TEXT,
    تاريخ_الانشاء TIMESTAMPTZ,
    حالة_اليوزر TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        s.رقم_الفرع,
        s.اسم_الفرع_ar,
        s.اسم_الفرع_en,
        s.تاريخ_الانشاء,
        s.حالة_اليوزر
    FROM بيانات_السيرفر s
    WHERE s.تاريخ_الانشاء BETWEEN تاريخ_البداية AND تاريخ_النهاية
    ORDER BY s.تاريخ_الانشاء DESC;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- إنشاء دالة لتصدير البيانات إلى CSV
-- ============================================

CREATE OR REPLACE FUNCTION تصدير_البيانات_إلى_CSV()
RETURNS TEXT AS $$
DECLARE
    result TEXT;
BEGIN
    SELECT string_agg(
        format(
            '%s,%s,%s,%s,%s,%s,%s',
            رقم_الفرع,
            اسم_الفرع_ar,
            اسم_الفرع_en,
            اسم_اليوزر,
            '***', -- الباسوورد لا يظهر في التصدير
            تاريخ_الانشاء,
            حالة_اليوزر
        ),
        E'
'
    )
    INTO result
    FROM بيانات_السيرفر;

    RETURN 'رقم_الفرع,اسم_الفرع_ar,اسم_الفرع_en,اسم_اليوزر,باسوورد,تاريخ_الانشاء,حالة_اليوزر
' || COALESCE(result, '');
END;
$$ LANGUAGE plpgsql;
