-- ============================================
-- الخطوة 1: إضافة الأعمدة الناقصة في جدول users
-- ============================================

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user',
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS is_trusted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS allowed_categories TEXT[] DEFAULT ARRAY['الكل', 'فلورينا', 'فرنشايز', 'جملة', 'موزع معتمد', 'اسكتشر', 'فيلانتو', 'الإدارة'],
  ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS email TEXT;

-- تحديث سياسات RLS للجدول users
DROP POLICY IF EXISTS "Can view own user data." ON public.users;
DROP POLICY IF EXISTS "Can update own user data." ON public.users;

-- المسؤول يرى الجميع، المستخدم العادي يرى نفسه فقط
CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
  FOR UPDATE USING (auth.uid() = id);

-- ============================================
-- الخطوة 2: إنشاء جدول server_data
-- ============================================

CREATE TABLE IF NOT EXISTS public.server_data (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  رقم_الفرع TEXT UNIQUE NOT NULL,
  اسم_الفرع_ar TEXT NOT NULL,
  اسم_الفرع_en TEXT NOT NULL,
  اسم_اليوزر TEXT NOT NULL,
  باسوورد TEXT NOT NULL,
  تاريخ_الانشاء TIMESTAMPTZ DEFAULT NOW(),
  حالة_اليوزر TEXT NOT NULL DEFAULT 'يعمل',
  تصنيف_الفرع TEXT DEFAULT 'فلورينا',
  طابعة_a4 TEXT,
  طابعة_فواتير TEXT,
  اسم_الشارع TEXT,
  اسم_المدينة TEXT,
  الرقم_الضريبي TEXT,
  المنطقة TEXT,
  serial_number INTEGER DEFAULT 100000
);

-- تفعيل RLS على جدول server_data
ALTER TABLE public.server_data ENABLE ROW LEVEL SECURITY;

-- سياسة القراءة: جميع المسجلين يستطيعون القراءة
DROP POLICY IF EXISTS "allow_authenticated_read" ON public.server_data;
CREATE POLICY "allow_authenticated_read"
  ON public.server_data FOR SELECT
  TO authenticated
  USING (true);

-- سياسة الكتابة والتعديل والحذف: المدير فقط
DROP POLICY IF EXISTS "allow_admin_insert" ON public.server_data;
CREATE POLICY "allow_admin_insert"
  ON public.server_data FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
      AND users.is_active = true
    )
  );

DROP POLICY IF EXISTS "allow_admin_update" ON public.server_data;
CREATE POLICY "allow_admin_update"
  ON public.server_data FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
      AND users.is_active = true
    )
  );

DROP POLICY IF EXISTS "allow_admin_delete" ON public.server_data;
CREATE POLICY "allow_admin_delete"
  ON public.server_data FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
      AND users.is_active = true
    )
  );

-- ============================================
-- الخطوة 3: تعيين حسابك كـ admin
-- استبدل 'your-email@example.com' بإيميلك الفعلي
-- ============================================

UPDATE public.users
SET role = 'admin',
    is_active = TRUE,
    is_trusted = TRUE,
    allowed_categories = ARRAY['الكل', 'فلورينا', 'فرنشايز', 'جملة', 'موزع معتمد', 'اسكتشر', 'فيلانتو', 'الإدارة']
WHERE id = (
  SELECT id FROM auth.users WHERE email = 'your-email@example.com' LIMIT 1
);

-- ============================================
-- الخطوة 4: إدخال بيانات تجريبية في server_data
-- ============================================

INSERT INTO public.server_data (رقم_الفرع, اسم_الفرع_ar, اسم_الفرع_en, اسم_اليوزر, باسوورد, حالة_اليوزر, تصنيف_الفرع, اسم_المدينة, المنطقة)
VALUES
  ('BR001', 'فرع الرياض', 'RIYADH BRANCH', 'riyadh_user', 'Pass@123', 'يعمل', 'فلورينا', 'الرياض', 'الرياض'),
  ('BR002', 'فرع جدة', 'JEDDAH BRANCH', 'jeddah_user', 'Pass@456', 'يعمل', 'فرنشايز', 'جدة', 'الحجاز'),
  ('BR003', 'فرع الدمام', 'DAMMAM BRANCH', 'dammam_user', 'Pass@789', 'الافتتاح قريبا', 'جملة', 'الدمام', 'الشرقية'),
  ('BR004', 'فرع مكة', 'MAKKAH BRANCH', 'makkah_user', 'Pass@321', 'مغلق مؤقتا', 'موزع معتمد', 'مكة المكرمة', 'الحجاز')
ON CONFLICT (رقم_الفرع) DO NOTHING;
