  void _showServerDialog({ServerData? serverToEdit, required List<ServerData> allServers}) {
    final branchNoController = TextEditingController(text: serverToEdit?.branchNo ?? '');
    final nameArController = TextEditingController(text: serverToEdit?.branchNameAr ?? '');
    final nameEnController = TextEditingController(text: serverToEdit?.branchNameEn ?? '');
    final usernameController = TextEditingController(text: serverToEdit?.username ?? '');
    
    // إخلاء حقل كلمة المرور في وضع التعديل لإدخال كلمة جديدة
    final passwordController = TextEditingController(); 
    
    final serialController = TextEditingController(text: serverToEdit?.serialNumber?.toString() ?? '');
    final streetController = TextEditingController(text: serverToEdit?.streetName ?? '');
    final cityController = TextEditingController(text: serverToEdit?.cityName ?? '');
    final taxNoController = TextEditingController(text: serverToEdit?.taxNo ?? '');
    final printerA4Controller = TextEditingController(text: serverToEdit?.printerA4 ?? '');
    final printerBillController = TextEditingController(text: serverToEdit?.printerBill ?? '');

    String selectedCategory = serverToEdit?.category ?? 'فلورينا';
    String selectedStatus = serverToEdit?.status ?? 'يعمل';
    String? selectedRegion = serverToEdit?.region;
    
    if (selectedRegion != null && !_regions.contains(selectedRegion)) {
      selectedRegion = null;
    }

    bool branchNoEdited = serverToEdit != null;
    bool obscurePassword = true;

    void updateAutoGeneratedFields(String category) {
      if (branchNoEdited && serverToEdit != null) return; 
      if (branchNoEdited) return; 

      int startNum = 1;
      if (category == 'اسكتشر') startNum = 300;
      else if (category == 'فرنشايز') startNum = 500;
      else if (category == 'موزع معتمد') startNum = 600;
      else if (category == 'فيلانتو') startNum = 900;
      else if (category == 'الإدارة') startNum = 1;

      final categoryServers = allServers.where((s) {
        if (category == 'فلورينا' || category == 'جملة') {
          return s.category == 'فلورينا' || s.category == 'جملة';
        }
        return s.category == category;
      }).toList();

      int nextNum = startNum;
      if (categoryServers.isNotEmpty) {
        int maxNum = 0;
        for (var s in categoryServers) {
          final numStr = s.branchNo.replaceAll(RegExp(r'\D'), '');
          final n = int.tryParse(numStr);
          if (n != null && n > maxNum) maxNum = n;
        }
        if (maxNum >= startNum) {
          nextNum = maxNum + 1;
        }
      }

      final hasBR = allServers.any((s) => s.branchNo.startsWith('BR'));
      String formattedNo = category == 'الإدارة' 
          ? 'h-$nextNum' 
          : (hasBR ? 'BR${nextNum.toString().padLeft(3, '0')}' : nextNum.toString());

      branchNoController.text = formattedNo;

      int nextSerial = 100000;
      if (allServers.isNotEmpty) {
        int maxSerial = 0;
        for (var s in allServers) {
          if (s.serialNumber != null && s.serialNumber! > maxSerial) {
            maxSerial = s.serialNumber!;
          }
        }
        nextSerial = maxSerial >= 100000 ? maxSerial + 100000 : 100000;
      }
      serialController.text = nextSerial.toString();
    }

    if (serverToEdit == null) {
      updateAutoGeneratedFields(selectedCategory);
    }

    nameEnController.addListener(() {
      final text = nameEnController.text.toUpperCase();
      if (text.length >= 4 && selectedCategory != 'الإدارة') {
        printerA4Controller.text = '${text.substring(0, 4)}BIGPRIN1';
        printerBillController.text = '${text.substring(0, 4)}SPRI';
      }
    });

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text(serverToEdit != null ? 'تعديل سيرفر (${serverToEdit.branchNo})' : 'إضافة سيرفر جديد', style: const TextStyle(fontWeight: FontWeight.bold)),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                DropdownButtonFormField<String>(
                  value: selectedCategory,
                  decoration: const InputDecoration(labelText: 'تصنيف الفرع'),
                  items: ['فلورينا', 'فرنشايز', 'جملة', 'موزع معتمد', 'اسكتشر', 'فيلانتو', 'الإدارة', 'كمبيوتر وملحقات'].map((c) {
                    return DropdownMenuItem(value: c, child: Text(c));
                  }).toList(),
                  onChanged: (val) {
                    setDialogState(() {
                      selectedCategory = val!;
                      if (serverToEdit == null) {
                        branchNoEdited = false;
                        updateAutoGeneratedFields(selectedCategory);
                      }
                    });
                  },
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: branchNoController,
                  decoration: const InputDecoration(labelText: 'رقم الفرع'),
                  onChanged: (v) => branchNoEdited = true,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: nameArController,
                  decoration: const InputDecoration(labelText: 'اسم الفرع بالعربي'),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: nameEnController,
                  decoration: const InputDecoration(labelText: 'اسم الفرع بالإنجليزي'),
                  textCapitalization: TextCapitalization.characters,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: usernameController,
                  decoration: const InputDecoration(labelText: 'اسم اليوزر'),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: passwordController,
                  obscureText: obscurePassword,
                  decoration: InputDecoration(
                    labelText: serverToEdit != null ? 'إدخال كلمة سر جديدة (اتركه فارغاً للاحتفاظ بالقديم)' : 'الباسوورد للسيرفر',
                    suffixIcon: IconButton(
                      icon: Icon(obscurePassword ? Icons.visibility_off : Icons.visibility),
                      onPressed: () {
                        setDialogState(() {
                          obscurePassword = !obscurePassword;
                        });
                      },
                    ),
                  ),
                ),
                if (selectedCategory != 'الإدارة') ...[
                  const SizedBox(height: 12),
                  TextField(
                    controller: serialController,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(labelText: 'التسلسل (Serial Number)'),
                  ),
                ],
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  value: selectedStatus,
                  decoration: const InputDecoration(labelText: 'حالة الفرع'),
                  items: ['يعمل', 'الافتتاح قريبا', 'مغلق مؤقتا', 'مغلق نهائيا'].map((s) {
                    return DropdownMenuItem(value: s, child: Text(s));
                  }).toList(),
                  onChanged: (val) => setDialogState(() => selectedStatus = val!),
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  value: selectedRegion,
                  decoration: const InputDecoration(labelText: 'المنطقة'),
                  items: _regions.map((r) => DropdownMenuItem(value: r, child: Text(r))).toList(),
                  onChanged: (val) => setDialogState(() => selectedRegion = val),
                ),
                const SizedBox(height: 12),
                const Divider(),
                const Text('بيانات إضافية', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, color: Colors.indigo)),
                const SizedBox(height: 8),
                TextField(
                  controller: streetController,
                  decoration: InputDecoration(
                    labelText: 'اسم الشارع',
                    suffixIcon: _getRequiredFields(selectedCategory)['street']! ? const Icon(Icons.star, color: Colors.red, size: 10) : null,
                  ),
                  enabled: _getRequiredFields(selectedCategory)['street']! || _getRequiredFields(selectedCategory)['city']!,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: cityController,
                  decoration: InputDecoration(
                    labelText: 'اسم المدينة',
                    suffixIcon: _getRequiredFields(selectedCategory)['city']! ? const Icon(Icons.star, color: Colors.red, size: 10) : null,
                  ),
                  enabled: _getRequiredFields(selectedCategory)['street']! || _getRequiredFields(selectedCategory)['city']!,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: taxNoController,
                  decoration: InputDecoration(
                    labelText: 'الرقم الضريبي',
                    suffixIcon: _getRequiredFields(selectedCategory)['taxNo']! ? const Icon(Icons.star, color: Colors.red, size: 10) : null,
                  ),
                  enabled: _getRequiredFields(selectedCategory)['taxNo']!,
                ),
                const SizedBox(height: 12),
                if (selectedCategory != 'الإدارة') ...[
                  const Divider(),
                  const Text('بيانات الطابعات', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, color: Colors.indigo)),
                  const SizedBox(height: 8),
                  TextField(
                    controller: printerA4Controller,
                    decoration: const InputDecoration(labelText: 'طابعة A4'),
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: printerBillController,
                    decoration: const InputDecoration(labelText: 'طابعة الفواتير'),
                  ),
                ],
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('إلغاء', style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold)),
            ),
            ElevatedButton(
              onPressed: () async {
                if (branchNoController.text.isEmpty ||
                    nameArController.text.isEmpty ||
                    nameEnController.text.isEmpty ||
                    usernameController.text.isEmpty ||
                    (serverToEdit == null && passwordController.text.isEmpty)) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('يرجى إدخال الحقول المطلوبة')),
                  );
                  return;
                }

                if (selectedCategory != 'الإدارة' && nameEnController.text.length < 4) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('اسم الفرع بالإنجليزية يجب أن يكون 4 أحرف على الأقل')),
                  );
                  return;
                }

                if (selectedCategory != 'الإدارة' && printerA4Controller.text.isNotEmpty && printerA4Controller.text.length != 12) {
                  showDialog(
                    context: context,
                    builder: (context) => AlertDialog(
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(25)),
                      title: const Row(
                        children: [
                          Icon(Icons.warning_amber_rounded, color: Colors.amber),
                          SizedBox(width: 8),
                          Text('خطأ في التنسيق', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                        ],
                      ),
                      content: const Text(
                        'يجب أن يتكون اسم طابعة A4 من 4 أحرف للفرع متبوعة بـ BIGPRIN1 (الإجمالي 12 حرف).',
                        style: TextStyle(fontSize: 14, color: Colors.grey),
                      ),
                      actions: [
                        ElevatedButton(
                          onPressed: () => Navigator.pop(context),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.amber,
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                          ),
                          child: const Text('موافق', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                        ),
                      ],
                    ),
                  );
                  return;
                }

                try {
                  final response = await Supabase.instance.client.from('server_data').select('id, رقم_الفرع, اسم_الفرع_ar, طابعة_a4, طابعة_فواتير');
                  final freshServers = (response as List).map((s) => ServerData.fromMap(s)).toList();
                  
                  if (selectedCategory != 'الإدارة') {
                    final duplicate = freshServers.firstWhere(
                      (s) => s.id != (serverToEdit?.id ?? -1) && 
                             ((s.printerA4 == printerA4Controller.text && printerA4Controller.text.isNotEmpty) ||
                              (s.printerBill == printerBillController.text && printerBillController.text.isNotEmpty)),
                      orElse: () => ServerData(id: 0, branchNo: '', category: '', branchNameAr: '', branchNameEn: '', username: '', encryptedPassword: '', status: '', createdAt: DateTime.now(), serialNumber: 0),
                    );

                    if (duplicate.id != 0) {
                      if (context.mounted) {
                        showDialog(
                          context: context,
                          builder: (context) => AlertDialog(
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(25)),
                            title: const Row(
                              children: [
                                Icon(Icons.info_outline_rounded, color: Colors.amber),
                                SizedBox(width: 8),
                                Text('تعارض في الطابعة', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                              ],
                            ),
                            content: Text(
                              'اسم الطابعة مستخدم مسبقاً في:\n(${duplicate.branchNo}) - ${duplicate.branchNameAr}',
                              style: const TextStyle(fontSize: 14, color: Colors.grey),
                            ),
                            actions: [
                              TextButton(
                                onPressed: () => Navigator.pop(context),
                                child: const Text('موافق', style: TextStyle(color: Colors.grey)),
                              ),
                            ],
                          ),
                        );
                      }
                      return;
                    }
                  }

                  String? encryptedPass;
                  if (passwordController.text.isNotEmpty) {
                    encryptedPass = encryptAESCryptoJS(passwordController.text, adminKey);
                  } else {
                    encryptedPass = serverToEdit?.encryptedPassword;
                  }

                  final dataPayload = {
                    'رقم_الفرع': branchNoController.text,
                    'تصنيف_الفرع': selectedCategory,
                    'اسم_الفرع_ar': nameArController.text,
                    'اسم_الفرع_en': nameEnController.text.toUpperCase(),
                    'اسم_اليوزر': usernameController.text,
                    'باسوورد': encryptedPass,
                    'حالة_اليوزر': selectedStatus,
                    'serial_number': selectedCategory == 'الإدارة' ? null : (int.tryParse(serialController.text) ?? 100000),
                    'المنطقة': selectedRegion,
                    'اسم_الشارع': streetController.text.isEmpty ? null : streetController.text,
                    'اسم_المدينة': cityController.text.isEmpty ? null : cityController.text,
                    'الرقم_الضريبي': selectedCategory == 'الإدارة' ? null : (taxNoController.text.isEmpty ? null : taxNoController.text),
                    'طابعة_a4': selectedCategory == 'الإدارة' ? null : printerA4Controller.text,
                    'طابعة_فواتير': selectedCategory == 'الإدارة' ? null : printerBillController.text,
                  };

                  if (serverToEdit == null) {
                    await Supabase.instance.client.from('server_data').insert(dataPayload);
                  } else {
                    await Supabase.instance.client.from('server_data').update(dataPayload).eq('id', serverToEdit.id);
                  }

                  if (context.mounted) {
                    Navigator.pop(context); 
                    ref.read(serverDataNotifierProvider.notifier).refreshServers();
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text(serverToEdit == null ? 'تم حفظ بيانات الفرع بنجاح' : 'تم تحديث بيانات الفرع بنجاح', style: const TextStyle(fontWeight: FontWeight.bold)),
                        backgroundColor: Colors.indigo[600],
                        behavior: SnackBarBehavior.floating,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                      ),
                    );
                  }
                } catch (e) {
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('حدث خطأ أثناء الحفظ: $e')),
                    );
                  }
                }
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
              child: Text(serverToEdit == null ? 'إضافة' : 'حفظ التعديلات', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }
