import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:aescryptojs/aescryptojs.dart';
import '../models/server_data.dart';

class ServerDialog extends StatefulWidget {
  final ServerData? serverToEdit;
  final List<ServerData> allServers;
  final VoidCallback onSaved;

  const ServerDialog({
    super.key,
    this.serverToEdit,
    required this.allServers,
    required this.onSaved,
  });

  @override
  State<ServerDialog> createState() => _ServerDialogState();
}

class _ServerDialogState extends State<ServerDialog> {
  static const adminKey = String.fromEnvironment('ADMIN_KEY', defaultValue: 'sols');

  late TextEditingController branchNoController;
  late TextEditingController nameArController;
  late TextEditingController nameEnController;
  late TextEditingController usernameController;
  late TextEditingController passwordController;
  late TextEditingController serialController;
  late TextEditingController streetController;
  late TextEditingController cityController;
  late TextEditingController taxNoController;
  late TextEditingController printerA4Controller;
  late TextEditingController printerBillController;

  String selectedCategory = 'فلورينا';
  String selectedStatus = 'يعمل';
  String? selectedRegion;
  bool branchNoEdited = false;
  bool obscurePassword = true;

  final List<String> _regions = [
    '1-المدينة المنورة',
    '1-المنطقة الوسطى',
    '2-الرياض',
    '2-الدمام',
    '3-الجنوبية - أبها',
    '4-جدة',
    '4-الغربية - مكة',
    '5-الشمالية تبوك',
    '5-الطائف'
  ];

  @override
  void initState() {
    super.initState();
    final s = widget.serverToEdit;
    branchNoController = TextEditingController(text: s?.branchNo ?? '');
    nameArController = TextEditingController(text: s?.branchNameAr ?? '');
    nameEnController = TextEditingController(text: s?.branchNameEn ?? '');
    usernameController = TextEditingController(text: s?.username ?? '');
    passwordController = TextEditingController();
    serialController = TextEditingController(text: s?.serialNumber?.toString() ?? '');
    streetController = TextEditingController(text: s?.streetName ?? '');
    cityController = TextEditingController(text: s?.cityName ?? '');
    taxNoController = TextEditingController(text: s?.taxNo ?? '');
    printerA4Controller = TextEditingController(text: s?.printerA4 ?? '');
    printerBillController = TextEditingController(text: s?.printerBill ?? '');

    selectedCategory = s?.category ?? 'فلورينا';
    selectedStatus = s?.status ?? 'يعمل';
    selectedRegion = s?.region;
    
    if (selectedRegion != null && !_regions.contains(selectedRegion)) {
      selectedRegion = null;
    }

    branchNoEdited = s != null;

    if (s == null) {
      updateAutoGeneratedFields(selectedCategory);
    }

    nameEnController.addListener(() {
      final text = nameEnController.text.toUpperCase();
      if (text.length >= 4 && selectedCategory != 'الإدارة') {
        printerA4Controller.text = '${text.substring(0, 4)}BIGPRIN1';
        printerBillController.text = '${text.substring(0, 4)}SPRI';
      }
    });
  }

  @override
  void dispose() {
    branchNoController.dispose();
    nameArController.dispose();
    nameEnController.dispose();
    usernameController.dispose();
    passwordController.dispose();
    serialController.dispose();
    streetController.dispose();
    cityController.dispose();
    taxNoController.dispose();
    printerA4Controller.dispose();
    printerBillController.dispose();
    super.dispose();
  }

  Map<String, bool> _getRequiredFields(String category) {
    if (category == 'فرنشايز' || category == 'فيلانتو') {
      return {'street': true, 'city': true, 'taxNo': true};
    } else if (category == 'فلورينا' || category == 'جملة') {
      return {'street': false, 'city': true, 'taxNo': false};
    } else {
      return {'street': false, 'city': false, 'taxNo': false};
    }
  }

  void updateAutoGeneratedFields(String category) {
    if (branchNoEdited && widget.serverToEdit != null) return; 
    if (branchNoEdited) return; 

    int startNum = 1;
    if (category == 'اسكتشر') startNum = 300;
    else if (category == 'فرنشايز') startNum = 500;
    else if (category == 'موزع معتمد') startNum = 600;
    else if (category == 'فيلانتو') startNum = 900;
    else if (category == 'الإدارة') startNum = 1;

    final categoryServers = widget.allServers.where((s) {
      if (category == 'فلورينا' || category == 'جملة') {
        return s.category == 'فلورينا' || s.category == 'جملة';
      }
      return s.category == category;
    }).toList();

    int nextNum = startNum;
    if (categoryServers.isNotEmpty) {
      int maxNum = 0;
      for (var s in categoryServers) {
        final numStr = s.branchNo.replaceAll(RegExp(r'\D'), '');
        final n = int.tryParse(numStr);
        if (n != null && n > maxNum) maxNum = n;
      }
      if (maxNum >= startNum) {
        nextNum = maxNum + 1;
      }
    }

    final hasBR = widget.allServers.any((s) => s.branchNo.startsWith('BR'));
    String formattedNo = category == 'الإدارة' 
        ? 'h-$nextNum' 
        : (hasBR ? 'BR${nextNum.toString().padLeft(3, '0')}' : nextNum.toString());

    branchNoController.text = formattedNo;

    int nextSerial = 100000;
    if (widget.allServers.isNotEmpty) {
      int maxSerial = 0;
      for (var s in widget.allServers) {
        if (s.serialNumber != null && s.serialNumber! > maxSerial) {
          maxSerial = s.serialNumber!;
        }
      }
      nextSerial = maxSerial >= 100000 ? maxSerial + 100000 : 100000;
    }
    serialController.text = nextSerial.toString();
  }

  InputDecoration _customDecoration({required String label, IconData? icon, Widget? suffix}) {
    return InputDecoration(
      labelText: label,
      labelStyle: const TextStyle(color: Colors.indigo, fontSize: 14),
      prefixIcon: icon != null ? Icon(icon, color: Colors.indigo) : null,
      suffixIcon: suffix,
      filled: true,
      fillColor: Colors.indigo.withOpacity(0.03),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(15), borderSide: BorderSide.none),
      enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(15), borderSide: BorderSide(color: Colors.indigo.withOpacity(0.1))),
      focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(15), borderSide: const BorderSide(color: Colors.indigo, width: 1.5)),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.serverToEdit != null;
    final reqFields = _getRequiredFields(selectedCategory);

    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      elevation: 10,
      backgroundColor: Colors.transparent,
      child: Container(
        decoration: BoxDecoration(
          color: Theme.of(context).scaffoldBackgroundColor,
          borderRadius: BorderRadius.circular(24),
          boxShadow: [
            BoxShadow(color: Colors.black.withOpacity(0.1), blurRadius: 20, offset: const Offset(0, 10)),
          ],
        ),
        constraints: const BoxConstraints(maxWidth: 500, maxHeight: 800),
        child: Column(
          children: [
            Container(
              padding: const EdgeInsets.all(20),
              decoration: const BoxDecoration(
                gradient: LinearGradient(colors: [Colors.indigo, Colors.blueAccent], begin: Alignment.topLeft, end: Alignment.bottomRight),
                borderRadius: BorderRadius.only(topLeft: Radius.circular(24), topRight: Radius.circular(24)),
              ),
              child: Row(
                children: [
                  Icon(isEditing ? Icons.edit_note_rounded : Icons.add_circle_outline_rounded, color: Colors.white, size: 28),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      isEditing ? 'تعديل بيانات السيرفر (${widget.serverToEdit!.branchNo})' : 'إضافة سيرفر جديد',
                      style: const TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close, color: Colors.white),
                    onPressed: () => Navigator.pop(context),
                    padding: EdgeInsets.zero,
                    constraints: const BoxConstraints(),
                  ),
                ],
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    DropdownButtonFormField<String>(
                      value: selectedCategory,
                      decoration: _customDecoration(label: 'تصنيف الفرع', icon: Icons.category_rounded),
                      items: ['فلورينا', 'فرنشايز', 'جملة', 'موزع معتمد', 'اسكتشر', 'فيلانتو', 'الإدارة', 'كمبيوتر وملحقات']
                          .map((c) => DropdownMenuItem(value: c, child: Text(c, style: const TextStyle(fontWeight: FontWeight.w600))))
                          .toList(),
                      onChanged: (val) {
                        setState(() {
                          selectedCategory = val!;
                          if (!isEditing) {
                            branchNoEdited = false;
                            updateAutoGeneratedFields(selectedCategory);
                          }
                        });
                      },
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: branchNoController,
                      decoration: _customDecoration(label: 'رقم الفرع', icon: Icons.numbers_rounded),
                      onChanged: (v) => branchNoEdited = true,
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: nameArController,
                      decoration: _customDecoration(label: 'اسم الفرع بالعربي', icon: Icons.store_mall_directory_rounded),
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: nameEnController,
                      decoration: _customDecoration(label: 'اسم الفرع بالإنجليزي', icon: Icons.store_mall_directory_outlined),
                      textCapitalization: TextCapitalization.characters,
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: usernameController,
                      decoration: _customDecoration(label: 'اسم اليوزر', icon: Icons.person_rounded),
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: passwordController,
                      obscureText: obscurePassword,
                      decoration: _customDecoration(
                        label: isEditing ? 'إدخال كلمة سر جديدة (اتركه فارغاً للاحتفاظ بالقديم)' : 'كلمة المرور',
                        icon: Icons.lock_rounded,
                        suffix: IconButton(
                          icon: Icon(obscurePassword ? Icons.visibility_off_rounded : Icons.visibility_rounded, color: Colors.indigo),
                          onPressed: () => setState(() => obscurePassword = !obscurePassword),
                        ),
                      ),
                    ),
                    if (selectedCategory != 'الإدارة') ...[
                      const SizedBox(height: 16),
                      TextField(
                        controller: serialController,
                        keyboardType: TextInputType.number,
                        decoration: _customDecoration(label: 'التسلسل (Serial Number)', icon: Icons.tag_rounded),
                      ),
                    ],
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: DropdownButtonFormField<String>(
                            value: selectedStatus,
                            decoration: _customDecoration(label: 'حالة الفرع', icon: Icons.info_rounded),
                            items: ['يعمل', 'الافتتاح قريبا', 'مغلق مؤقتا', 'مغلق نهائيا']
                                .map((s) => DropdownMenuItem(value: s, child: Text(s)))
                                .toList(),
                            onChanged: (val) => setState(() => selectedStatus = val!),
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: DropdownButtonFormField<String>(
                            value: selectedRegion,
                            decoration: _customDecoration(label: 'المنطقة', icon: Icons.map_rounded),
                            items: _regions.map((r) => DropdownMenuItem(value: r, child: Text(r, overflow: TextOverflow.ellipsis))).toList(),
                            onChanged: (val) => setState(() => selectedRegion = val),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),
                    const Row(
                      children: [
                        Icon(Icons.more_horiz_rounded, color: Colors.indigo, size: 20),
                        SizedBox(width: 8),
                        Text('بيانات إضافية', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.indigo)),
                      ],
                    ),
                    const Divider(height: 24, thickness: 1),
                    TextField(
                      controller: streetController,
                      decoration: _customDecoration(
                        label: 'اسم الشارع',
                        icon: Icons.add_road_rounded,
                        suffix: reqFields['street']! ? const Icon(Icons.star, color: Colors.redAccent, size: 12) : null,
                      ),
                      enabled: reqFields['street']! || reqFields['city']!,
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: TextField(
                            controller: cityController,
                            decoration: _customDecoration(
                              label: 'اسم المدينة',
                              icon: Icons.location_city_rounded,
                              suffix: reqFields['city']! ? const Icon(Icons.star, color: Colors.redAccent, size: 12) : null,
                            ),
                            enabled: reqFields['street']! || reqFields['city']!,
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: TextField(
                            controller: taxNoController,
                            decoration: _customDecoration(
                              label: 'الرقم الضريبي',
                              icon: Icons.receipt_long_rounded,
                              suffix: reqFields['taxNo']! ? const Icon(Icons.star, color: Colors.redAccent, size: 12) : null,
                            ),
                            enabled: reqFields['taxNo']!,
                          ),
                        ),
                      ],
                    ),
                    if (selectedCategory != 'الإدارة') ...[
                      const SizedBox(height: 24),
                      const Row(
                        children: [
                          Icon(Icons.print_rounded, color: Colors.indigo, size: 20),
                          SizedBox(width: 8),
                          Text('بيانات الطابعات', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.indigo)),
                        ],
                      ),
                      const Divider(height: 24, thickness: 1),
                      TextField(
                        controller: printerA4Controller,
                        decoration: _customDecoration(label: 'طابعة A4', icon: Icons.print_outlined),
                      ),
                      const SizedBox(height: 16),
                      TextField(
                        controller: printerBillController,
                        decoration: _customDecoration(label: 'طابعة الفواتير', icon: Icons.receipt_rounded),
                      ),
                    ],
                  ],
                ),
              ),
            ),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
              decoration: BoxDecoration(
                color: Colors.grey.shade50,
                borderRadius: const BorderRadius.only(bottomLeft: Radius.circular(24), bottomRight: Radius.circular(24)),
                border: Border(top: BorderSide(color: Colors.grey.shade200)),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Navigator.pop(context),
                    style: TextButton.styleFrom(
                      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: const Text('إلغاء', style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold, fontSize: 16)),
                  ),
                  const SizedBox(width: 12),
                  ElevatedButton(
                    onPressed: _saveData,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.indigo,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 12),
                      elevation: 2,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: Text(isEditing ? 'حفظ التعديلات' : 'إضافة الفرع', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, letterSpacing: 0.5)),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _saveData() async {
    final isEditing = widget.serverToEdit != null;

    if (branchNoController.text.isEmpty ||
        nameArController.text.isEmpty ||
        nameEnController.text.isEmpty ||
        usernameController.text.isEmpty ||
        (!isEditing && passwordController.text.isEmpty)) {
      _showError('يرجى إدخال الحقول المطلوبة الأساسية');
      return;
    }

    if (selectedCategory != 'الإدارة' && nameEnController.text.length < 4) {
      _showError('اسم الفرع بالإنجليزية يجب أن يكون 4 أحرف على الأقل');
      return;
    }

    if (selectedCategory != 'الإدارة' && printerA4Controller.text.isNotEmpty && printerA4Controller.text.length != 12) {
      _showPrinterErrorDialog();
      return;
    }

    try {
      final response = await Supabase.instance.client.from('server_data').select('id, رقم_الفرع, اسم_الفرع_ar, طابعة_a4, طابعة_فواتير');
      final freshServers = (response as List).map((s) => ServerData.fromMap(s)).toList();
      
      if (selectedCategory != 'الإدارة') {
        final duplicate = freshServers.firstWhere(
          (s) => s.id != (widget.serverToEdit?.id ?? -1) && 
                 ((s.printerA4 == printerA4Controller.text && printerA4Controller.text.isNotEmpty) ||
                  (s.printerBill == printerBillController.text && printerBillController.text.isNotEmpty)),
          orElse: () => ServerData(id: 0, branchNo: '', category: '', branchNameAr: '', branchNameEn: '', username: '', encryptedPassword: '', status: '', createdAt: DateTime.now(), serialNumber: 0),
        );

        if (duplicate.id != 0) {
          if (mounted) {
            showDialog(
              context: context,
              builder: (context) => AlertDialog(
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
                title: const Row(
                  children: [
                    Icon(Icons.info_outline_rounded, color: Colors.amber, size: 28),
                    SizedBox(width: 12),
                    Text('تعارض في الطابعة', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20)),
                  ],
                ),
                content: Text(
                  'اسم الطابعة مستخدم مسبقاً في:\n(${duplicate.branchNo}) - ${duplicate.branchNameAr}',
                  style: const TextStyle(fontSize: 15, color: Colors.black87),
                ),
                actions: [
                  TextButton(
                    onPressed: () => Navigator.pop(context),
                    child: const Text('موافق', style: TextStyle(color: Colors.indigo, fontWeight: FontWeight.bold)),
                  ),
                ],
              ),
            );
          }
          return;
        }
      }

      String? encryptedPass;
      if (passwordController.text.isNotEmpty) {
        encryptedPass = encryptAESCryptoJS(passwordController.text, adminKey);
      } else {
        encryptedPass = widget.serverToEdit?.encryptedPassword;
      }

      final reqFields = _getRequiredFields(selectedCategory);
      final bool isStreetCityEnabled = reqFields['street']! || reqFields['city']!;
      final bool isTaxNoEnabled = reqFields['taxNo']!;
      final bool isSerialPrintersHidden = selectedCategory == 'الإدارة';

      final dataPayload = {
        'رقم_الفرع': branchNoController.text,
        'تصنيف_الفرع': selectedCategory,
        'اسم_الفرع_ar': nameArController.text,
        'اسم_الفرع_en': nameEnController.text.toUpperCase(),
        'اسم_اليوزر': usernameController.text,
        'باسوورد': encryptedPass,
        'حالة_اليوزر': selectedStatus,
        'serial_number': isSerialPrintersHidden ? null : int.tryParse(serialController.text),
        'المنطقة': selectedRegion,
        'اسم_الشارع': (!isStreetCityEnabled || streetController.text.isEmpty) ? null : streetController.text,
        'اسم_المدينة': (!isStreetCityEnabled || cityController.text.isEmpty) ? null : cityController.text,
        'الرقم_الضريبي': (!isTaxNoEnabled || taxNoController.text.isEmpty) ? null : taxNoController.text,
        'طابعة_a4': (isSerialPrintersHidden || printerA4Controller.text.isEmpty) ? null : printerA4Controller.text,
        'طابعة_فواتير': (isSerialPrintersHidden || printerBillController.text.isEmpty) ? null : printerBillController.text,
      };

      if (!isEditing) {
        await Supabase.instance.client.from('server_data').insert(dataPayload);
      } else {
        await Supabase.instance.client.from('server_data').update(dataPayload).eq('id', widget.serverToEdit!.id);
      }

      if (mounted) {
        Navigator.pop(context); 
        widget.onSaved();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.check_circle_rounded, color: Colors.white),
                const SizedBox(width: 12),
                Text(isEditing ? 'تم تحديث بيانات الفرع بنجاح' : 'تم إضافة الفرع بنجاح', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              ],
            ),
            backgroundColor: Colors.teal.shade600,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            margin: const EdgeInsets.all(16),
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        _showError('حدث خطأ أثناء الحفظ: $e');
      }
    }
  }

  void _showError(String msg) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            const Icon(Icons.error_outline_rounded, color: Colors.white),
            const SizedBox(width: 12),
            Expanded(child: Text(msg, style: const TextStyle(fontWeight: FontWeight.bold))),
          ],
        ),
        backgroundColor: Colors.redAccent,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(16),
      ),
    );
  }

  void _showPrinterErrorDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
        title: const Row(
          children: [
            Icon(Icons.warning_amber_rounded, color: Colors.amber, size: 28),
            SizedBox(width: 12),
            Text('خطأ في تنسيق الطابعة', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
          ],
        ),
        content: const Text(
          'يجب أن يتكون اسم طابعة A4 من 4 أحرف للفرع متبوعة بـ BIGPRIN1 (الإجمالي 12 حرف).',
          style: TextStyle(fontSize: 15, height: 1.5),
        ),
        actions: [
          ElevatedButton(
            onPressed: () => Navigator.pop(context),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.amber.shade700,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            ),
            child: const Text('فهمت', style: TextStyle(fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }
}
