import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/server_data.dart';
import '../utils/print_utils.dart';
import 'package:aescryptojs/aescryptojs.dart';
import 'package:http/http.dart' as http;
import 'package:csv/csv.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../services/server_notifier.dart';
import '../services/metadata_notifier.dart';

class ServerListScreen extends ConsumerStatefulWidget {
  const ServerListScreen({super.key});

  @override
  ConsumerState<ServerListScreen> createState() => _ServerListScreenState();
}

class _ServerListScreenState extends ConsumerState<ServerListScreen> {
  final List<String> _categories = [
    'الكل',
    'فلورينا',
    'فرنشايز',
    'جملة',
    'موزع معتمد',
    'اسكتشر',
    'فيلانتو',
    'الإدارة',
    'كمبيوتر وملحقات',
    'جرد الأجهزة'
  ];

  final List<String> _regions = [
    '1-المدينة المنورة',
    '1-المنطقة الوسطى',
    '2-الرياض',
    '2-الدمام',
    '3-الجنوبية - أبها',
    '4-جدة',
    '4-الغربية - مكة',
    '5-الشمالية تبوك',
    '5-الطائف'
  ];

  static const adminKey = String.fromEnvironment('ADMIN_KEY', defaultValue: 'sols');

  Map<String, bool> _getRequiredFields(String category) {
    if (category == 'فرنشايز' || category == 'فيلانتو') {
      return {'street': true, 'city': true, 'taxNo': true};
    } else if (category == 'فلورينا' || category == 'جملة') {
      return {'street': false, 'city': true, 'taxNo': false};
    } else {
      return {'street': false, 'city': false, 'taxNo': false};
    }
  }

  void _showServerDialog({ServerData? serverToEdit, required List<ServerData> allServers}) {
    final branchNoController = TextEditingController(text: serverToEdit?.branchNo ?? '');
    final nameArController = TextEditingController(text: serverToEdit?.branchNameAr ?? '');
    final nameEnController = TextEditingController(text: serverToEdit?.branchNameEn ?? '');
    final usernameController = TextEditingController(text: serverToEdit?.username ?? '');
    
    // إخلاء حقل كلمة المرور في وضع التعديل لإدخال كلمة جديدة
    final passwordController = TextEditingController(); 
    
    final serialController = TextEditingController(text: serverToEdit?.serialNumber?.toString() ?? '');
    final streetController = TextEditingController(text: serverToEdit?.streetName ?? '');
    final cityController = TextEditingController(text: serverToEdit?.cityName ?? '');
    final taxNoController = TextEditingController(text: serverToEdit?.taxNo ?? '');
    final printerA4Controller = TextEditingController(text: serverToEdit?.printerA4 ?? '');
    final printerBillController = TextEditingController(text: serverToEdit?.printerBill ?? '');

    String selectedCategory = serverToEdit?.category ?? 'فلورينا';
    String selectedStatus = serverToEdit?.status ?? 'يعمل';
    String? selectedRegion = serverToEdit?.region;
    
    if (selectedRegion != null && !_regions.contains(selectedRegion)) {
      selectedRegion = null;
    }

    bool branchNoEdited = serverToEdit != null;
    bool obscurePassword = true;

    void updateAutoGeneratedFields(String category) {
      if (branchNoEdited && serverToEdit != null) return; 
      if (branchNoEdited) return; 

      int startNum = 1;
      if (category == 'اسكتشر') startNum = 300;
      else if (category == 'فرنشايز') startNum = 500;
      else if (category == 'موزع معتمد') startNum = 600;
      else if (category == 'فيلانتو') startNum = 900;
      else if (category == 'الإدارة') startNum = 1;

      final categoryServers = allServers.where((s) {
        if (category == 'فلورينا' || category == 'جملة') {
          return s.category == 'فلورينا' || s.category == 'جملة';
        }
        return s.category == category;
      }).toList();

      int nextNum = startNum;
      if (categoryServers.isNotEmpty) {
        int maxNum = 0;
        for (var s in categoryServers) {
          final numStr = s.branchNo.replaceAll(RegExp(r'\D'), '');
          final n = int.tryParse(numStr);
          if (n != null && n > maxNum) maxNum = n;
        }
        if (maxNum >= startNum) {
          nextNum = maxNum + 1;
        }
      }

      final hasBR = allServers.any((s) => s.branchNo.startsWith('BR'));
      String formattedNo = category == 'الإدارة' 
          ? 'h-$nextNum' 
          : (hasBR ? 'BR${nextNum.toString().padLeft(3, '0')}' : nextNum.toString());

      branchNoController.text = formattedNo;

      int nextSerial = 100000;
      if (allServers.isNotEmpty) {
        int maxSerial = 0;
        for (var s in allServers) {
          if (s.serialNumber != null && s.serialNumber! > maxSerial) {
            maxSerial = s.serialNumber!;
          }
        }
        nextSerial = maxSerial >= 100000 ? maxSerial + 100000 : 100000;
      }
      serialController.text = nextSerial.toString();
    }

    if (serverToEdit == null) {
      updateAutoGeneratedFields(selectedCategory);
    }

    nameEnController.addListener(() {
      final text = nameEnController.text.toUpperCase();
      if (text.length >= 4 && selectedCategory != 'الإدارة') {
        printerA4Controller.text = '${text.substring(0, 4)}BIGPRIN1';
        printerBillController.text = '${text.substring(0, 4)}SPRI';
      }
    });

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text(serverToEdit != null ? 'تعديل سيرفر (${serverToEdit.branchNo})' : 'إضافة سيرفر جديد', style: const TextStyle(fontWeight: FontWeight.bold)),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                DropdownButtonFormField<String>(
                  value: selectedCategory,
                  decoration: const InputDecoration(labelText: 'تصنيف الفرع'),
                  items: ['فلورينا', 'فرنشايز', 'جملة', 'موزع معتمد', 'اسكتشر', 'فيلانتو', 'الإدارة', 'كمبيوتر وملحقات'].map((c) {
                    return DropdownMenuItem(value: c, child: Text(c));
                  }).toList(),
                  onChanged: (val) {
                    setDialogState(() {
                      selectedCategory = val!;
                      if (serverToEdit == null) {
                        branchNoEdited = false;
                        updateAutoGeneratedFields(selectedCategory);
                      }
                    });
                  },
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: branchNoController,
                  decoration: const InputDecoration(labelText: 'رقم الفرع'),
                  onChanged: (v) => branchNoEdited = true,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: nameArController,
                  decoration: const InputDecoration(labelText: 'اسم الفرع بالعربي'),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: nameEnController,
                  decoration: const InputDecoration(labelText: 'اسم الفرع بالإنجليزي'),
                  textCapitalization: TextCapitalization.characters,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: usernameController,
                  decoration: const InputDecoration(labelText: 'اسم اليوزر'),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: passwordController,
                  obscureText: obscurePassword,
                  decoration: InputDecoration(
                    labelText: serverToEdit != null ? 'إدخال كلمة سر جديدة (اتركه فارغاً للاحتفاظ بالقديم)' : 'الباسوورد للسيرفر',
                    suffixIcon: IconButton(
                      icon: Icon(obscurePassword ? Icons.visibility_off : Icons.visibility),
                      onPressed: () {
                        setDialogState(() {
                          obscurePassword = !obscurePassword;
                        });
                      },
                    ),
                  ),
                ),
                if (selectedCategory != 'الإدارة') ...[
                  const SizedBox(height: 12),
                  TextField(
                    controller: serialController,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(labelText: 'التسلسل (Serial Number)'),
                  ),
                ],
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  value: selectedStatus,
                  decoration: const InputDecoration(labelText: 'حالة الفرع'),
                  items: ['يعمل', 'الافتتاح قريبا', 'مغلق مؤقتا', 'مغلق نهائيا'].map((s) {
                    return DropdownMenuItem(value: s, child: Text(s));
                  }).toList(),
                  onChanged: (val) => setDialogState(() => selectedStatus = val!),
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  value: selectedRegion,
                  decoration: const InputDecoration(labelText: 'المنطقة'),
                  items: _regions.map((r) => DropdownMenuItem(value: r, child: Text(r))).toList(),
                  onChanged: (val) => setDialogState(() => selectedRegion = val),
                ),
                const SizedBox(height: 12),
                const Divider(),
                const Text('بيانات إضافية', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, color: Colors.indigo)),
                const SizedBox(height: 8),
                TextField(
                  controller: streetController,
                  decoration: InputDecoration(
                    labelText: 'اسم الشارع',
                    suffixIcon: _getRequiredFields(selectedCategory)['street']! ? const Icon(Icons.star, color: Colors.red, size: 10) : null,
                  ),
                  enabled: _getRequiredFields(selectedCategory)['street']! || _getRequiredFields(selectedCategory)['city']!,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: cityController,
                  decoration: InputDecoration(
                    labelText: 'اسم المدينة',
                    suffixIcon: _getRequiredFields(selectedCategory)['city']! ? const Icon(Icons.star, color: Colors.red, size: 10) : null,
                  ),
                  enabled: _getRequiredFields(selectedCategory)['street']! || _getRequiredFields(selectedCategory)['city']!,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: taxNoController,
                  decoration: InputDecoration(
                    labelText: 'الرقم الضريبي',
                    suffixIcon: _getRequiredFields(selectedCategory)['taxNo']! ? const Icon(Icons.star, color: Colors.red, size: 10) : null,
                  ),
                  enabled: _getRequiredFields(selectedCategory)['taxNo']!,
                ),
                const SizedBox(height: 12),
                if (selectedCategory != 'الإدارة') ...[
                  const Divider(),
                  const Text('بيانات الطابعات', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, color: Colors.indigo)),
                  const SizedBox(height: 8),
                  TextField(
                    controller: printerA4Controller,
                    decoration: const InputDecoration(labelText: 'طابعة A4'),
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: printerBillController,
                    decoration: const InputDecoration(labelText: 'طابعة الفواتير'),
                  ),
                ],
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('إلغاء', style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold)),
            ),
            ElevatedButton(
              onPressed: () async {
                if (branchNoController.text.isEmpty ||
                    nameArController.text.isEmpty ||
                    nameEnController.text.isEmpty ||
                    usernameController.text.isEmpty ||
                    (serverToEdit == null && passwordController.text.isEmpty)) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('يرجى إدخال الحقول المطلوبة')),
                  );
                  return;
                }

                if (selectedCategory != 'الإدارة' && nameEnController.text.length < 4) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('اسم الفرع بالإنجليزية يجب أن يكون 4 أحرف على الأقل')),
                  );
                  return;
                }

                if (selectedCategory != 'الإدارة' && printerA4Controller.text.isNotEmpty && printerA4Controller.text.length != 12) {
                  showDialog(
                    context: context,
                    builder: (context) => AlertDialog(
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(25)),
                      title: const Row(
                        children: [
                          Icon(Icons.warning_amber_rounded, color: Colors.amber),
                          SizedBox(width: 8),
                          Text('خطأ في التنسيق', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                        ],
                      ),
                      content: const Text(
                        'يجب أن يتكون اسم طابعة A4 من 4 أحرف للفرع متبوعة بـ BIGPRIN1 (الإجمالي 12 حرف).',
                        style: TextStyle(fontSize: 14, color: Colors.grey),
                      ),
                      actions: [
                        ElevatedButton(
                          onPressed: () => Navigator.pop(context),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.amber,
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                          ),
                          child: const Text('موافق', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                        ),
                      ],
                    ),
                  );
                  return;
                }

                try {
                  final response = await Supabase.instance.client.from('server_data').select('id, رقم_الفرع, اسم_الفرع_ar, طابعة_a4, طابعة_فواتير');
                  final freshServers = (response as List).map((s) => ServerData.fromMap(s)).toList();
                  
                  if (selectedCategory != 'الإدارة') {
                    final duplicate = freshServers.firstWhere(
                      (s) => s.id != (serverToEdit?.id ?? -1) && 
                             ((s.printerA4 == printerA4Controller.text && printerA4Controller.text.isNotEmpty) ||
                              (s.printerBill == printerBillController.text && printerBillController.text.isNotEmpty)),
                      orElse: () => ServerData(id: 0, branchNo: '', category: '', branchNameAr: '', branchNameEn: '', username: '', encryptedPassword: '', status: '', createdAt: DateTime.now(), serialNumber: 0),
                    );

                    if (duplicate.id != 0) {
                      if (context.mounted) {
                        showDialog(
                          context: context,
                          builder: (context) => AlertDialog(
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(25)),
                            title: const Row(
                              children: [
                                Icon(Icons.info_outline_rounded, color: Colors.amber),
                                SizedBox(width: 8),
                                Text('تعارض في الطابعة', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                              ],
                            ),
                            content: Text(
                              'اسم الطابعة مستخدم مسبقاً في:\n(${duplicate.branchNo}) - ${duplicate.branchNameAr}',
                              style: const TextStyle(fontSize: 14, color: Colors.grey),
                            ),
                            actions: [
                              TextButton(
                                onPressed: () => Navigator.pop(context),
                                child: const Text('موافق', style: TextStyle(color: Colors.grey)),
                              ),
                            ],
                          ),
                        );
                      }
                      return;
                    }
                  }

                  String? encryptedPass;
                  if (passwordController.text.isNotEmpty) {
                    encryptedPass = encryptAESCryptoJS(passwordController.text, adminKey);
                  } else {
                    encryptedPass = serverToEdit?.encryptedPassword;
                  }

                  final dataPayload = {
                    'رقم_الفرع': branchNoController.text,
                    'تصنيف_الفرع': selectedCategory,
                    'اسم_الفرع_ar': nameArController.text,
                    'اسم_الفرع_en': nameEnController.text.toUpperCase(),
                    'اسم_اليوزر': usernameController.text,
                    'باسوورد': encryptedPass,
                    'حالة_اليوزر': selectedStatus,
                    'serial_number': selectedCategory == 'الإدارة' ? null : (int.tryParse(serialController.text) ?? 100000),
                    'المنطقة': selectedRegion,
                    'اسم_الشارع': streetController.text.isEmpty ? null : streetController.text,
                    'اسم_المدينة': cityController.text.isEmpty ? null : cityController.text,
                    'الرقم_الضريبي': selectedCategory == 'الإدارة' ? null : (taxNoController.text.isEmpty ? null : taxNoController.text),
                    'طابعة_a4': selectedCategory == 'الإدارة' ? null : printerA4Controller.text,
                    'طابعة_فواتير': selectedCategory == 'الإدارة' ? null : printerBillController.text,
                  };

                  if (serverToEdit == null) {
                    await Supabase.instance.client.from('server_data').insert(dataPayload);
                  } else {
                    await Supabase.instance.client.from('server_data').update(dataPayload).eq('id', serverToEdit.id);
                  }

                  if (context.mounted) {
                    Navigator.pop(context); 
                    ref.read(serverDataNotifierProvider.notifier).refreshServers();
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text(serverToEdit == null ? 'تم حفظ بيانات الفرع بنجاح' : 'تم تحديث بيانات الفرع بنجاح', style: const TextStyle(fontWeight: FontWeight.bold)),
                        backgroundColor: Colors.indigo[600],
                        behavior: SnackBarBehavior.floating,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                      ),
                    );
                  }
                } catch (e) {
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('حدث خطأ أثناء الحفظ: $e')),
                    );
                  }
                }
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
              child: Text(serverToEdit == null ? 'إضافة' : 'حفظ التعديلات', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }

  Color _getStatusColor(String status) {
    switch (status) {
      case 'يعمل':
        return Colors.green.withOpacity(0.12);
      case 'مغلق نهائيا':
        return Colors.red.withOpacity(0.12);
      case 'مغلق مؤقتا':
        return Colors.orange.withOpacity(0.12);
      case 'الافتتاح قريبا':
        return Colors.blue.withOpacity(0.12);
      default:
        return Colors.grey.withOpacity(0.12);
    }
  }

  Color _getStatusTextColor(String status) {
    switch (status) {
      case 'يعمل':
        return Colors.green[800]!;
      case 'مغلق نهائيا':
        return Colors.red[800]!;
      case 'مغلق مؤقتا':
        return Colors.orange[800]!;
      case 'الافتتاح قريبا':
        return Colors.blue[800]!;
      default:
        return Colors.grey[800]!;
    }
  }

  void _showPasswordDialog(ServerData server) {
    String decryptedPass = '';
    try {
      if (server.encryptedPassword.isNotEmpty) {
        decryptedPass = decryptAESCryptoJS(server.encryptedPassword, adminKey);
      }
    } catch (e) {
      decryptedPass = 'تعذر فك التشفير';
    }

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Row(
          children: [
            Icon(Icons.vpn_key_outlined, color: Colors.indigo),
            SizedBox(width: 8),
            Text('كلمة المرور', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('كلمة المرور للسيرفر (${server.branchNo}):', style: const TextStyle(fontSize: 14)),
            const SizedBox(height: 15),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              decoration: BoxDecoration(
                color: Colors.grey[100],
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: Colors.grey[300]!),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Expanded(
                    child: SelectableText(
                      decryptedPass.isEmpty ? 'غير متوفرة' : decryptedPass,
                      style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, letterSpacing: 1.5),
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.copy, color: Colors.indigo),
                    tooltip: 'نسخ كلمة المرور',
                    onPressed: () {
                      Clipboard.setData(ClipboardData(text: decryptedPass));
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: const Text('تم النسخ للحافظة بنجاح!', style: TextStyle(fontWeight: FontWeight.bold)),
                          backgroundColor: Colors.green[600],
                          behavior: SnackBarBehavior.floating,
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                        ),
                      );
                      Navigator.pop(context);
                    },
                  ),
                ],
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('إغلاق', style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final metadataAsync = ref.watch(metadataProvider);
    final serversAsync = ref.watch(serverDataNotifierProvider);

    return DefaultTabController(
      length: _categories.length,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('إدارة الفروع والسيرفرات', style: TextStyle(fontWeight: FontWeight.bold)),
          backgroundColor: Colors.indigo,
          foregroundColor: Colors.white,
          actions: [
            IconButton(onPressed: () => ref.read(serverDataNotifierProvider.notifier).refreshServers(), icon: const Icon(Icons.refresh)),
            serversAsync.when(
              data: (allServers) => IconButton(
                onPressed: () => _showServerDialog(allServers: allServers), 
                icon: const Icon(Icons.add_circle_outline)
              ),
              loading: () => const SizedBox.shrink(),
              error: (_, __) => const SizedBox.shrink(),
            )
          ],
          bottom: TabBar(
            isScrollable: true,
            labelColor: Colors.white,
            unselectedLabelColor: Colors.white70,
            indicatorColor: Colors.amber,
            tabs: _categories.map((c) => Tab(text: c)).toList(),
          ),
        ),
        body: metadataAsync.when(
          loading: () => const Center(child: CircularProgressIndicator()),
          error: (e, st) => Center(child: Text('خطأ في جلب بيانات المستخدم: $e')),
          data: (metadata) {
            if (metadata?.role != 'admin') {
              return const Center(
                child: Text(
                  'ليس لديك صلاحية للوصول إلى هذه الصفحة',
                  style: TextStyle(fontSize: 18, color: Colors.red, fontWeight: FontWeight.bold),
                ),
              );
            }
            return serversAsync.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, st) => Center(child: Text('خطأ في جلب السيرفرات: $e')),
              data: (allServers) => TabBarView(
                children: _categories.map((category) {
                  if (category == 'كمبيوتر وملحقات') {
                    return const GoogleSheetTableWidget(
                      csvUrl: 'https://docs.google.com/spreadsheets/d/1NycN1P-ZcMjEvR9vqx0GyOjfaq4FWpK2N3srpv4pWp4/export?format=csv&gid=0',
                      allowedIndices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
                      customHeaders: ["رقم الفرع", "اسم الفرع", "المنطقة", "الكمبيوتر", "الشاشة", "الهارد", "المعالج", "الرام", "الطابعة الكبيرة", "الطابعة الصغيرة", "الماسح الضوئي", "نوع الانترنت", "رقم الهاتف", "DVR", "البصمة", "الموقع"],
                    );
                  } else if (category == 'جرد الأجهزة') {
                    return const GoogleSheetTableWidget(
                      csvUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT5ngevFTz20Fi7JG_JKIe4ZnYmVEGpUZtL_5INutfSNI3PqCO7F3J9rkdDWN9LtA6pLnisoar0-v7C/pub?gid=806274198&single=true&output=csv',
                      allowedIndices: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                      customHeaders: ["اسم الفرع", "عدد الكاميرات", "سعة الهارد", "عدد الماوس", "الكيبورد", "الاسكانر", "درج الكاشير", "الشاشة الكبيرة", "الشاشة الصغيرة", "شاشة اللمس", "UPS", "السويتش", "جهاز البصمة"],
                    );
                  }

                  final filteredServers = category == 'الكل' 
                      ? allServers 
                      : allServers.where((s) => s.category == category).toList();
                  
                  if (filteredServers.isEmpty) {
                    return const Center(child: Text('لا توجد سيرفرات في هذا التصنيف', style: TextStyle(fontSize: 16, color: Colors.grey)));
                  }

                  return RefreshIndicator(
                    onRefresh: () => ref.read(serverDataNotifierProvider.notifier).refreshServers(),
                    child: ListView.builder(
                      itemCount: filteredServers.length,
                      itemBuilder: (context, index) {
                        final server = filteredServers[index];
                        return Card(
                          margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                          elevation: 0,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(15),
                            side: BorderSide(color: Colors.grey[200]!, width: 1),
                          ),
                          child: ListTile(
                            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                            leading: CircleAvatar(
                              backgroundColor: Colors.indigo.withOpacity(0.1),
                              foregroundColor: Colors.indigo,
                              child: Text(server.branchNo, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold)),
                            ),
                            title: Text(server.branchNameAr, style: const TextStyle(fontWeight: FontWeight.bold)),
                            subtitle: Padding(
                              padding: const EdgeInsets.only(top: 8.0),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Text(server.category, style: TextStyle(color: Colors.grey[600], fontSize: 12)),
                                  const SizedBox(width: 8),
                                  Container(
                                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                                    decoration: BoxDecoration(
                                      color: _getStatusColor(server.status),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    child: Text(
                                      server.status,
                                      style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: _getStatusTextColor(server.status)),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            trailing: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                IconButton(
                                  icon: const Icon(Icons.vpn_key_outlined, color: Colors.amber, size: 22),
                                  tooltip: 'عرض كلمة المرور',
                                  onPressed: () => _showPasswordDialog(server),
                                ),
                                IconButton(
                                  icon: Icon(Icons.print_outlined, color: Colors.blue[600], size: 22),
                                  tooltip: 'طباعة نموذج',
                                  onPressed: () {
                                    final supported = ['فرنشايز', 'فيلانتو', 'فلورينا', 'جملة', 'اسكتشر', 'موزع معتمد'];
                                    if (supported.contains(server.category)) {
                                      PrintUtils.printBranchFoundation(server);
                                    } else {
                                      ScaffoldMessenger.of(context).showSnackBar(
                                        const SnackBar(content: Text('سيتم تزويد بيانات الطباعة لهذا التصنيف لاحقاً')),
                                      );
                                    }
                                  },
                                ),
                                IconButton(
                                  icon: Icon(Icons.edit_outlined, color: Colors.green[600], size: 22),
                                  tooltip: 'تعديل',
                                  onPressed: () => _showServerDialog(serverToEdit: server, allServers: allServers),
                                ),
                                IconButton(
                                  icon: Icon(Icons.delete_outline, color: Colors.red[600], size: 22),
                                  tooltip: 'حذف',
                                  onPressed: () => _showDeleteConfirmation(server),
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
                  );
                }).toList(),
              ),
            );
          },
        ),
      ),
    );
  }

  void _showDeleteConfirmation(ServerData server) {
    final passwordController = TextEditingController();
    String? errorMsg;

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          title: Row(
            children: [
              const Icon(Icons.warning_amber_rounded, color: Colors.red),
              const SizedBox(width: 10),
              Expanded(child: Text('حذف الفرع (${server.branchNo})', style: const TextStyle(fontWeight: FontWeight.bold))),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text('أنت على وشك حذف هذا الفرع نهائياً. يرجى إدخال كلمة المرور للتأكيد:'),
              if (errorMsg != null)
                Padding(
                  padding: const EdgeInsets.only(top: 10),
                  child: Text(errorMsg!, style: const TextStyle(color: Colors.red, fontSize: 12, fontWeight: FontWeight.bold)),
                ),
              const SizedBox(height: 15),
              TextField(
                controller: passwordController,
                obscureText: true,
                decoration: InputDecoration(
                  labelText: 'كلمة المرور',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  filled: true,
                  fillColor: Colors.grey[100],
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('إلغاء', style: TextStyle(color: Colors.grey)),
            ),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.red,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
              ),
              onPressed: () async {
                if (passwordController.text != adminKey) {
                  setDialogState(() => errorMsg = 'كلمة المرور غير صحيحة');
                  return;
                }
                try {
                  await Supabase.instance.client
                      .from('server_data')
                      .delete()
                      .eq('id', server.id);
                  if (context.mounted) {
                    Navigator.pop(context);
                    ref.read(serverDataNotifierProvider.notifier).refreshServers();
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: const Text('تم حذف الفرع بنجاح', style: TextStyle(fontWeight: FontWeight.bold)),
                        backgroundColor: Colors.green[600],
                        behavior: SnackBarBehavior.floating,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                      ),
                    );
                  }
                } catch (e) {
                  setDialogState(() => errorMsg = 'خطأ في الحذف: $e');
                }
              },
              child: const Text('حذف نهائي', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }
}

class GoogleSheetTableWidget extends StatefulWidget {
  final String csvUrl;
  final List<int>? allowedIndices;
  final List<String>? customHeaders;

  const GoogleSheetTableWidget({
    super.key,
    required this.csvUrl,
    this.allowedIndices,
    this.customHeaders,
  });

  @override
  State<GoogleSheetTableWidget> createState() => _GoogleSheetTableWidgetState();
}

class _GoogleSheetTableWidgetState extends State<GoogleSheetTableWidget> {
  List<Map<String, String>> _data = [];
  List<String> _headers = [];
  bool _isLoading = true;
  String _error = '';

  @override
  void initState() {
    super.initState();
    _fetchCsv();
  }

  Future<void> _fetchCsv() async {
    try {
      final url = '${widget.csvUrl}&t=${DateTime.now().millisecondsSinceEpoch}';
      final response = await http.get(Uri.parse(url), headers: {
        'Pragma': 'no-cache',
        'Cache-Control': 'no-cache',
      });
      
      if (response.statusCode == 200) {
        final decoded = utf8.decode(response.bodyBytes);
        final rows = CsvDecoder().convert(decoded);
        
        if (rows.length < 2) {
          setState(() {
            _data = [];
            _headers = widget.customHeaders ?? [];
            _isLoading = false;
          });
          return;
        }

        List<String> headers = widget.customHeaders ?? rows.first.map((e) => e.toString()).toList();
        List<int> indices = widget.allowedIndices ?? List.generate(headers.length, (i) => i);

        List<Map<String, String>> parsedData = [];
        for (int i = 1; i < rows.length; i++) {
          final row = rows[i];
          Map<String, String> rowData = {};
          for (int j = 0; j < indices.length; j++) {
            final colIdx = indices[j];
            rowData[headers[j]] = (colIdx < row.length) ? row[colIdx].toString() : '';
          }
          parsedData.add(rowData);
        }

        setState(() {
          _data = parsedData;
          _headers = headers;
          _isLoading = false;
        });
      } else {
        setState(() {
          _error = 'خطأ في جلب البيانات من المصدر';
          _isLoading = false;
        });
      }
    } catch (e) {
      setState(() {
        _error = 'حدث خطأ: $e';
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) return const Center(child: CircularProgressIndicator());
    if (_error.isNotEmpty) return Center(child: Text(_error, style: const TextStyle(color: Colors.red)));
    if (_data.isEmpty) return const Center(child: Text('لا توجد بيانات', style: TextStyle(color: Colors.grey)));

    return RefreshIndicator(
      onRefresh: _fetchCsv,
      child: LayoutBuilder(
        builder: (context, constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            physics: const AlwaysScrollableScrollPhysics(),
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: ConstrainedBox(
                constraints: BoxConstraints(minWidth: constraints.maxWidth),
                child: DataTable(
                  headingRowColor: MaterialStateProperty.all(Colors.indigo.withOpacity(0.05)),
                  dataRowMaxHeight: 60,
                  columns: _headers.map((h) => DataColumn(
                    label: Text(h, style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.indigo)),
                  )).toList(),
                  rows: _data.map((row) {
                    return DataRow(
                      cells: _headers.map((h) {
                        return DataCell(
                          Container(
                            padding: const EdgeInsets.symmetric(vertical: 8),
                            child: SelectableText(row[h] ?? '', style: const TextStyle(fontSize: 13)),
                          ),
                        );
                      }).toList(),
                    );
                  }).toList(),
                ),
              ),
            ),
          );
        }
      ),
    );
  }
}
