-- ملف الترحيل (Migration) الثاني: إنشاء الجدول والسياسات وإدخال البيانات التجريبية

-- 1. إنشاء الجدول
CREATE TABLE public."server_data" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "رقم_الفرع" TEXT UNIQUE NOT NULL,
    "اسم_الفرع_ar" TEXT NOT NULL,
    "اسم_الفرع_en" TEXT NOT NULL,
    "اسم_اليوزر" TEXT NOT NULL,
    "باسوورد" TEXT NOT NULL, -- سيتم تخزين النص المشفر هنا
    "تاريخ_الانشاء" TIMESTAMPTZ DEFAULT NOW(),
    "حالة_اليوزر" TEXT NOT NULL CHECK ("حالة_اليوزر" IN ('الافتتاح قريبا', 'يعمل', 'مغلق مؤقتا', 'مغلق نهائياً'))
);

-- 2. تفعيل سياسة الأمان (RLS)
ALTER TABLE public."server_data" ENABLE ROW LEVEL SECURITY;

-- 3. سياسة القراءة: جميع المستخدمين المسجلين يمكنهم القراءة
CREATE POLICY "Can read server data" 
ON public."server_data" 
FOR SELECT 
TO authenticated 
USING (true);

-- 4. سياسة الكتابة والتعديل والحذف: فقط للمديرين
-- يفترض هذا أن حساب المدير يمتلك خاصية role = 'admin' بداخل user_metadata الخاصة به.
CREATE POLICY "Admins can manage server data" 
ON public."server_data" 
FOR ALL 
TO authenticated 
USING (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin')
WITH CHECK (auth.jwt() -> 'user_metadata' ->> 'role' = 'admin');

-- 5. إدخال بيانات تجريبية 
-- (كلمات المرور بالأسفل مشفرة بتشفير AES وتتطلب كلمة sols لفكها)
INSERT INTO public."server_data" 
("رقم_الفرع", "اسم_الفرع_ar", "اسم_الفرع_en", "اسم_اليوزر", "باسوورد", "حالة_اليوزر") VALUES
('BR001', 'الرياض', 'RIYADH', 'admin_riyadh', 'U2FsdGVkX1+vGj8P8D+E5h/yZ4A=', 'يعمل'),
('BR002', 'جدة', 'JEDDAH', 'user_jeddah', 'U2FsdGVkX1+vGj8P8D+E5h/yZ4A=', 'الافتتاح قريبا'),
('BR003', 'الدمام', 'DAMMAM', 'test_dammam', 'U2FsdGVkX1+vGj8P8D+E5h/yZ4A=', 'مغلق مؤقتا');
